config/routes.rb
Kennel::Application.routes.draw do

  scope '/mercury' do
    match ':type/:resource' => "mercury#resource"
    match 'snippets/:name/options' => "mercury#snippet_options"
    match 'snippets/:name/preview' => "mercury#snippet_preview"
  end

  root :to => "home#main"

  resources :pets do
    resources :photos
  end
  resources :posts
  resources :photos

  match 'gallery' => 'albums#index', :as => :gallery

  resources :albums do
    resources :photos
  end

  match 'admin' => 'admin/dashboard#home', :as => :admin
  match 'admin/settings' => 'admin/settings#show' , :as => :admin_settings
  match 'admin/settings/update' => 'admin/settings#update'

  namespace :admin do
    root :to => "dashboard#home"
    resources :photos
    resources :posts
    resources :albums do
      resources :photos
      collection do
        post 'uploader'
      end
    end
    resources :pets
    resources :people
    resources :static_pages
  end

  match '/pages/*path', :to => 'static_content#show', :via => :get, :as => 'static_page'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  include Rails.application.routes.url_helpers

  has_attached_file :image, :styles => {
    :large => "900x430#",
    :composer_large => "704x352#",
    :composer_medium => "352x352#",
    :composer_small => "176x176#",
    :medium => "220x175#",
    :admin_thumb => "270x175#",
    :slider => "568x372#",
    :thumb => "160x120#",
    :pet_title => "380x255#"
    }
  has_many :pet_photos
  has_many :pets, :through => :pet_photos
  has_and_belongs_to_many :albums, :uniq => true
  belongs_to :primary_album, :class_name => "Album"

  validates :caption, :length => { :maximum => 140}
  validates_attachment_presence :image
  validates_presence_of :image

  scope :unsorted, where(:album_id => nil) #FIXME
  scope :main, where(:on_main => true)

  paginates_per 54

  def to_jq_upload
    {
      "name" => image_file_name,
      "size" => image_file_size,
      "url" => image.url,
      "thumbnail_url" => image.url(:thumb),
      "delete_url" => admin_photo_path(:id => id),
      "delete_type" => "DELETE",
      "id" => id
    }
  end

  def next_photo(album)
    photos = album.photos.order('id ASC')
    photo = photos.where("photo_id > ?", id).first
    return photo.nil? ? photos.first : photo
  end

  def prev_photo(album)
    photos = album.photos.order('id DESC')
    photo = photos.where("photo_id < ?", id).first
    return photo.nil? ? photos.first : photo
  end

end

app/controllers/admin/photos_controller.rb
# -*- coding: utf-8 -*-
class Admin::PhotosController < Admin::ApplicationController
  before_filter :find_photo, :except => [:index, :new, :create]
  before_filter :find_albums, :only => [:new, :edit]
  cache_sweeper :photo_sweeper

  def index
      @photos = Photo.where(params[:search]).order('created_at DESC').page params[:page]
  end

  def show
  end

  def edit
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(params[:photo])
    @photo.save

    redirect_to admin_photos_path
  end

  def update
    if @photo.update_attributes(params[:photo])
        flash[:info] = "Фотография успешно обновлена"
    else
      flash[:error] = "Что-то пошло не так"
    end

    redirect_to session[:back_url] || admin_photos_path
  end

  def destroy
    @photo.destroy
    redirect_to :back
  end

  private
  def find_photo
    @photo = Photo.find(params[:id])
  end

  def find_albums
    @albums = Album.all
  end
end

app/controllers/photos_controller.rb
# -*- coding: utf-8 -*-
class PhotosController < ApplicationController

  def index
    @pet = Pet.find(params[:pet_id])
    @photos = @pet.photos.order("image_file_name ASC")
  end

  def show
    @photo = Photo.find(params[:id])
    if params[:pet_id]
      @pet = Pet.find(params[:pet_id])
      @photos = @pet.photos.order('id ASC')
    else
      if params[:album_id]
        @album = Album.find(params[:album_id])
      else
        @album = @photo.albums.first
      end
      @photos = @album.photos.order('id ASC')
    end
  end

end

app/helpers/photos_helper.rb
# -*- coding: utf-8 -*-
module PhotosHelper
  def caption(photo)
    return photo.caption if photo.caption.present? && !photo.caption.strip.empty?
    content_tag(:em, "Нет описания")
  end

  def composer_block(photos, pet=nil, album=nil)
    output = ""
    case photos.length

        when 10
          output << composer_thumb(photos.first, :composer_medium, pet, album)
          photos[1..8].each do |pho|
            output << composer_thumb(pho, :composer_small, pet, album)
          end
          output << composer_thumb(photos.last, :composer_medium, pet, album)

        when 9
          output << composer_thumb(photos.first, :composer_large, pet, album)
          photos[1..8].each do |pho|
            output << composer_thumb(pho, :composer_small, pet, album)
          end

        when 8
          photos.each do |pho|
            output << composer_thumb(pho, :composer_small, pet, album)
          end

        when 7
          photos.first(3).each do |pho|
            output << composer_thumb(pho, :composer_medium, pet, album)
          end
          photos.last(4).each do |pho|
            output << composer_thumb(pho, :composer_small, pet, album)
          end

        when 6
          output << composer_thumb(photos.first, :composer_large, pet, album)
          output << composer_thumb(photos[1], :composer_medium, pet, album)
          photos.last(4).each do |pho|
            output << composer_thumb(pho, :composer_small, pet, album)
          end

        when 5
          output << composer_thumb(photos.first, :composer_medium, pet, album)
          photos.last(4).each do |pho|
            output << composer_thumb(pho, :composer_small, pet, album)
          end

        when 4
          photos.each do |pho|
            output << composer_thumb(pho, :composer_medium, pet, album)
          end

        when 3
          output << composer_thumb(photos.first, :composer_large, pet, album)
          photos.last(2).each do |pho|
            output << composer_thumb(pho, :composer_medium, pet, album)
          end

        when 2
          photos.each do |pho|
            output << composer_thumb(pho, :composer_medium, pet, album)
          end

        when 1
      output << composer_thumb(photos.first, :composer_large, pet, album)

    end
    raw output
  end

  def composer_thumb(photo, style, pet, album)
    content_tag :div, :class => "photo-composer-thumb" do
      link_to( image_tag(photo.image.url(style)),
        (pet.present? ? pet_photo_path(pet, photo) : album_photo_path(album, photo)),
        :class => "photo-composer-thumb")
    end
  end
end

app/views/admin/photos/_form.html.erb
<%= form_for [:admin, photo], :validate => validate, :html => { :class => "form-horizontal" } do |f| %>

<%= hidden_field_tag :back_url, request.referer %>

<div class="row">
    <div class="span4">
      <div class="control-group">
         <label class="control-label">Описание</label>
         <div class="controls">
           <%= f.text_area :caption, :rows => "4", :class => "span3" %>
         </div>
      </div>

      <div class="control-group">
         <label class="control-label">Показывать на главной странице</label>
         <div class="controls">
           <%= f.check_box :on_main %>
         </div>
      </div>

      <div class="control-group">
         <label class="control-label">Файл</label>
         <div class="controls">
           <%= f.file_field :image, :class => "input-xlarge"  %>
         </div>
      </div>

      <div class="control-group">
        <label class="control-label">Собаки на фото</label>
        <div class="controls">
          <%= hidden_field_tag "photo[pet_ids][]", nil %>
          <% Pet.all.each do |pet| %>
              <label class="checkbox">
                <%= check_box_tag "photo[pet_ids][]", pet.id, photo.pets.include?(pet), :id => dom_id(pet) %>
                <%= "#{pet.name} #{pet.title}" %>
              </label>
          <% end %>
        </div>
      </div>
    </div>

    <% unless photo.new_record? %>
      <div class="span5">
         <%= image_tag photo.image.url(:medium), :class => "thumbnail pull-right main-row" %>
         <div class="pull-right cleared">
           <% if !@photo.albums.empty? %>
             <h4>Фото находится в альбомах:</h4>
              <ul class="pull-right cleared unstyled">
                <% @photo.albums.each do |album| %>
                  <li><%= link_to album.name, admin_album_path(album) %></li>
                <% end %>
              </ul>
            <% end %>
         </div>
      </div>
    <% end %>
</div>

  <div class="form-actions">
    <%= f.submit "Сохранить", :class => 'btn btn-primary' %>
    <%= link_to "Отмена", session[:back_url], :class => "btn btn-small" %>
  </div>

<% end %>

app/views/admin/photos/_sidenav.html.erb
<% active ||= '' %>
<div class="span2">
    <nav class="well" style="padding: 8px 0;">
        <ul class="nav nav-list">
          <li class="nav-header">Фотографии</li>
          <li class="<%== 'active' if active == 'all-photos' %>">
            <%= link_to "Фотографии", admin_photos_path %>
          </li>
          <li class="<%== 'active' if active == 'slider-photos' %>">
            <%= link_to "Слайдер", admin_photos_path(:search => {:on_main => true}) %>
          </li>
          <li class="<%== 'active' if active == 'all-albums' %>">
            <%= link_to "Альбомы", admin_albums_path %>
          </li>
          <li class="<%== 'active' if active == 'tech-albums' %>">
            <%= link_to "Технические альбомы", admin_albums_path(:hidden => true) %>
          </li>
          <li class="divider"></li>
          <li class="<%== 'active' if active == 'new-album' %>">
            <%= link_to "Добавить альбом", new_admin_album_path %>
          </li>
          <li class="<%== 'active' if active == 'new-photo' %>">
            <%= link_to "Добавить фотографию", new_admin_photo_path %>
          </li>
        </ul>
    </nav>
</div>

app/views/admin/photos/edit.html.erb
<div class="row">
<%= render "sidenav" %>

  <div class="span10">
    <h1>Редактировать фотографию</h1>
    <%= render "form", :photo => @photo, :validate => false %>
  </div>
</div>

app/views/admin/photos/index.html.erb
<div class="row">
  <%= render "sidenav", :active => params[:search].present? ? "slider-photos" : "all-photos" %>

  <div class="span10">
  	<%= link_to "Добавить фотографию", new_admin_photo_path, :class => "btn pull-right" %>

    <h1>Фотографии <%= "на главной" if params[:search].present? %></h1>
    <%= render "admin/shared/photos", :photos => @photos %>
    <%= paginate @photos %>
  </div>
</div>

app/views/admin/photos/new.html.erb
<div class="row">
  <%= render "sidenav", :active => "new-photo" %>

  <div class="span10">
    <h1>Новая фотография</h1>
    <%= render "form", :photo => @photo, :validate => true %>
  </div>
</div>

app/views/admin/photos/show.html.erb
<h1>Admin::PhotosController#show</h1>
<p>Find me in app/views/admin/photos_controller/show.html.erb</p>