config/routes.rb
Kennel::Application.routes.draw do

  scope '/mercury' do
    match ':type/:resource' => "mercury#resource"
    match 'snippets/:name/options' => "mercury#snippet_options"
    match 'snippets/:name/preview' => "mercury#snippet_preview"
  end

  root :to => "home#main"

  resources :pets do
    resources :photos
  end
  resources :posts
  resources :photos

  match 'gallery' => 'albums#index', :as => :gallery

  resources :albums do
    resources :photos
  end

  match 'admin' => 'admin/dashboard#home', :as => :admin
  match 'admin/settings' => 'admin/settings#show' , :as => :admin_settings
  match 'admin/settings/update' => 'admin/settings#update'

  namespace :admin do
    root :to => "dashboard#home"
    resources :photos
    resources :posts
    resources :albums do
      resources :photos
      collection do
        post 'uploader'
      end
    end
    resources :pets
    resources :people
    resources :static_pages
  end

  match '/pages/*path', :to => 'static_content#show', :via => :get, :as => 'static_page'

end

app/views/shared/_footer.html.erb
<footer>
  <p>
    2012 Все права защищены | Developed by <a href="http://twitter.com/fodoj">Fodoj</a>
  </p>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="navbar clearfix">
    <% if current_page?(root_url) %>
      <%= link_to image_tag("logo2.png"), root_url, :id => "logo", :class => "brand" %>
    <% else %>
      <%= link_to image_tag("logoa.jpg"), root_url, :id => "logo", :class => "brand" %>
    <% end %>

    <ul class="nav nav-pills">
      <li class=" <%== 'active' if current_page?(posts_path) %>">
        <%= link_to "Новости", posts_path %>
      </li>
      <li class=" <%== 'active' if current_page?(pets_path) %>">
        <%= link_to "Питомцы", pets_path %>
      </li>
      <li class=" <%== 'active' if current_page?(gallery_path) %>">
        <%= link_to "Галерея", gallery_path %>
      </li>
      <% StaticPage.all.each do |page| %>
        <li><%= link_to page.name,  static_page_path(:path => page.slug) %></li>
      <% end %>
    </ul>
  </div>

</header>

app/views/shared/_notification.html.erb
<div class="alert alert-<%= name %>">
  <a class='close' data-dismiss="alert">×</a>
  <%= msg %>
</div>