config/routes.rb
Kennel::Application.routes.draw do

  scope '/mercury' do
    match ':type/:resource' => "mercury#resource"
    match 'snippets/:name/options' => "mercury#snippet_options"
    match 'snippets/:name/preview' => "mercury#snippet_preview"
  end

  root :to => "home#main"

  resources :pets do
    resources :photos
  end
  resources :posts
  resources :photos

  match 'gallery' => 'albums#index', :as => :gallery

  resources :albums do
    resources :photos
  end

  match 'admin' => 'admin/dashboard#home', :as => :admin
  match 'admin/settings' => 'admin/settings#show' , :as => :admin_settings
  match 'admin/settings/update' => 'admin/settings#update'

  namespace :admin do
    root :to => "dashboard#home"
    resources :photos
    resources :posts
    resources :albums do
      resources :photos
      collection do
        post 'uploader'
      end
    end
    resources :pets
    resources :people
    resources :static_pages
  end

  match '/pages/*path', :to => 'static_content#show', :via => :get, :as => 'static_page'

end

app/models/pet.rb
# -*- coding: utf-8 -*-
class Pet < ActiveRecord::Base
  has_many :pet_photos
  has_many :photos, :through => :pet_photos

  belongs_to :owner, :class_name => "Person"
  belongs_to :breeder, :class_name => "Person"
  belongs_to :kennel, :class_name => "Person"

  belongs_to :mother, :class_name => "Pet"
  belongs_to :father, :class_name => "Pet"
  has_many :children, :class_name => "Pet"

  has_attached_file :avatar, :styles => {
    :large => "600x600",
    :medium => "270x175#",
    :slider => "568x372#",
    :title => "380x255#",
    :pedigree_parent => "358x278#",
    :pedigree_grandparent => "168x96#",
    :pedigree_elder => "100x68#",
    :thumb => "172x140#" }, :default_url => "missing_thumb.png"

  accepts_nested_attributes_for :photos, :allow_destroy => true
  accepts_nested_attributes_for :owner

  delegate :name, :to => :owner, :prefix => true
  delegate :name, :to => :breeder, :prefix => true
  delegate :name, :to => :kennel, :prefix => true

  validates :name, :presence => true
  validate :parents_gender

  scope :dogs, where(:sex => true)
  scope :puppies, where(:puppy => true)
  scope :bitches, where(:sex => false)
  scope :my, where(:owned => true)


  class << self
    def extend_parents(pets)
      elder = []

      pets.each do |pet|
        elder += pet.parents if pet.present?
      end

      elder
    end
  end

  def parents
    [father, mother]
  end

  def descendants
    children + children.map(&:children).flatten
  end

  def children
    Pet.find(:all, :conditions => ['father_id=? or mother_id=?', id, id])
  end

  def next_photo(photo)
    photos.where("photo_id > ?", photo.id).first || photos.first
  end

  def prev_photo(photo)
    photo = photos.where("photo_id < ?", photo.id).first
    return photo.nil? ? photos.first : photo
  end


  def assign_person(person_type, person_name)
    return unless person_type.present? & person_name.present?

    person = Person.find_or_create_by_name(person_name)
    update_attribute(person_type, person)
    person.has_role(person_type)
  end

  def assign_persons(persons = {})
    persons.each do |person_type, person_name|
      assign_person(person_type, person_name)
    end
  end

  def assign_parents(mather_name, father_name)
    if mather_name.present?
      update_attribute(:mother, Pet.find_or_create_by_name_and_sex(mather_name, false))
    end

    if father_name.present?
      update_attribute(:father, Pet.find_or_create_by_name_and_sex(father_name, true))
    end
  end

  private
    def parents_gender
      errors.add(:mother, "Кобель не может быть матерью") if mother && mother.sex
      errors.add(:father, "Сука не может быть отцом") if father && !father.sex
    end
end

app/controllers/admin/pets_controller.rb
# -*- coding: utf-8 -*-
class Admin::PetsController < Admin::ApplicationController
  before_filter :find_pet, :except => [:index, :new, :create]

  def index
    @pets = Pet.where(params[:search])
  end

  def show
    @photos = @pet.photos
  end

  def new
    @pet = Pet.new
    @mothers = Pet.bitches
    @fathers = Pet.dogs
  end

  def create
    @pet = Pet.new(params[:pet])

    if @pet.save
      @pet.assign_persons({
        :owner => params[:new_owner_name],
        :breeder => params[:new_breeder_name],
        :kennel => params[:new_kennel_name]
      })
      @pet.assign_parents(params[:new_mother_name], params[:new_father_name])
      flash[:info] = "Добавлен питомец '#{@pet.name}'"
    end

    redirect_to session[:back_url] || admin_pets_path
  end

  def edit
    descendants = @pet.descendants
    @mothers = Pet.bitches.where('id != ?', @pet.id) - descendants
    @fathers = Pet.dogs.where('id != ?', @pet.id) - descendants
  end

  def update
    if @pet.update_attributes(params[:pet])
      @pet.assign_persons({
        :owner => params[:new_owner_name],
        :breeder => params[:new_breeder_name],
        :kennel => params[:new_kennel_name]
      })
      @pet.assign_parents(params[:new_mother_name], params[:new_father_name])
      flash[:info] = "Питомец '#{@pet.name}' успешно обновлен"
    else
      flash[:error] = "Что-то пошло не так"
    end
    redirect_to session[:back_url] || admin_pets_path
  end

  def destroy
    @pet.destroy
    flash[:info] = "Питомец '#{@pet.name}' удалён"
    redirect_to :back
  end

  private
    def find_pet
      @pet = Pet.find(params[:id])
    end
end

app/controllers/pets_controller.rb
# -*- coding: utf-8 -*-
class PetsController < ApplicationController

  def index
    @pets = Pet.my
  end

  def show
    @pet = Pet.find(params[:id])
    @previews = @pet.photos.order("RANDOM()").last(4)
    @parents = @pet.parents
    @grandparents = Pet.extend_parents(@pet.parents)
    @elders = Pet.extend_parents(@grandparents)
  end

end

app/helpers/pets_helper.rb
# -*- coding: utf-8 -*-
module PetsHelper
  def pet_sex(pet)
    pet.sex ? "Кобель" : "Сука"
  end

  def pet_owner(pet)
    if pet.owned
      AdminSettings.owner_name # taichiman: There may be 'if' with bug
      # OWNER_NAME
    else
      pet.owner_name if pet.owner.present?
    end
  end

  def active_admin_pets_menu(searcher)
    pets_strings_by_search(searcher, "my-pets", "puppy-pets", "all-pets")
  end

  def admin_pets_header(searcher)
    pets_strings_by_search(searcher, "Мои питомцы", "Щенки", "Питомцы")
  end

  def pets_strings_by_search(searcher, owned, puppy, default)
    if searcher.present?
      if searcher[:owned].present? && searcher[:owned]
        owned
      elsif searcher[:puppy].present? && searcher[:puppy]
        puppy
      end
    else
      default
    end
  end
end

app/views/admin/pets/_form.html.erb
<%= nested_form_for [:admin, pet], :validate => true, :html => { :class => "form-horizontal pet-form", :multipart => true } do |f| %>

  <div class="row">
      <div class="span5">
          <div class="control-group">
             <label class="control-label">Кличка</label>
             <div class="controls">
               <%= f.text_field :name %>
             </div>
          </div>

          <div class="control-group">
             <label class="control-label">Титулы</label>
             <div class="controls">
               <%= f.text_field :title %>
             </div>
          </div>

         <div class="control-group">
             <label class="control-label">Дата рождения</label>
             <div class="controls date-select">
               <%= f.date_select :born, :start_year => 2000 %>
             </div>
          </div>

          <div class="control-group">
             <label class="control-label">Щенок</label>
             <div class="controls date-select">
               <%= f.check_box :puppy %>
             </div>
          </div>

          <div class="control-group">
             <label class="control-label">Мой питомец</label>
             <div class="controls date-select">
               <%= f.check_box :owned %>
             </div>
          </div>

          <div class="control-group">
             <label class="control-label">Пол</label>
             <div class="controls">

               <div class="btn-group pet-type-buttons" data-toggle="buttons-radio">
                 <a class="btn <%== 'active' if pet.sex %>" data-sex="true" title="Кобель" href="#">
                   Кобель
                  </a>
                  <a class="btn <%== 'active' if !pet.sex %>" data-sex="false" title="Сука" href="#">
                    Сука
                  </a>
               </div>

                <%= f.hidden_field :sex, :class => 'pet-sex-value' %>

             </div>
          </div>

          <div class="control-group">
             <label class="control-label">Окрас</label>
             <div class="controls">
               <%= f.text_field :color %>
             </div>
          </div>

          <div class="control-group">
             <label class="control-label">Владелец</label>
             <div class="controls">
               <%= f.select  :owner_id, Person.owners.collect {|p| [ p.name, p.id ] }, { :include_blank => "Нет владельца"} %>
               <%= text_field_tag :new_owner_name, "", :class => "new-person-input" %>
               <a href="" class="pull-right pet-new-person" id="new-owner-link">Добавить нового</a>
             </div>
          </div>

          <div class="control-group">
             <label class="control-label">Заводчик</label>
             <div class="controls">
               <%= f.select :breeder_id, Person.breeders.collect {|p| [ p.name, p.id ] }, { :include_blank => "Нет заводчика"}  %>
               <%= text_field_tag :new_breeder_name, "", :class => "new-person-input" %>
               <a href="" class="pull-right pet-new-person" id="new-breeder-link">Добавить нового</a>
             </div>
          </div>

          <div class="control-group">
             <label class="control-label">Питомник</label>
             <div class="controls">
               <%= f.select :kennel_id, Person.kennels.collect {|p| [ p.name, p.id ] }, { :include_blank => "Нет питомника"} %>
               <%= text_field_tag :new_kennel_name, "", :class => "new-person-input" %>
               <a href="" class="pull-right pet-new-person" id="new-kennel-link">Добавить новый</a>
             </div>
          </div>

          <div class="control-group">
             <label class="control-label">Мать</label>
             <div class="controls">
               <%= f.select :mother_id, @mothers.collect {|p| [ p.name, p.id ] }, { :include_blank => "Нет матери"}  %>
               <%= text_field_tag :new_mother_name, "", :class => "new-person-input" %>
               <a href="" class="pull-right pet-new-person" id="new-mother-link">Добавить</a>
             </div>
          </div>

          <div class="control-group">
             <label class="control-label">Отец</label>
             <div class="controls">
               <%= f.select :father_id, @fathers.collect {|p| [ p.name, p.id ] }, { :include_blank => "Нет отца"} %>
               <%= text_field_tag :new_father_name, "", :class => "new-person-input" %>
               <a href="" class="pull-right pet-new-person" id="new-father-link">Добавить</a>
             </div>
          </div>

          <div class="control-group">
             <label class="control-label">Описание</label>
             <div class="controls">
               <%= f.text_area :description, :rows => "20", :class => "editor span7" %>
             </div>
          </div>

      </div>

      <div class="span4 photos-block">
           <h3>Фото</h3>

           <% if pet.avatar.present? %>
               <div class="row">
                 <%= image_tag pet.avatar.url(:medium), :class => "thumbnail" %>
               </div>
           <% end %>

           <div class="main-row">
             <%= f.file_field :avatar %>
           </div>


      </div>
  </div>

  <div class="row">
           <h3 class="main-row">Отмеченные фотографии</h3>
           <% if pet.photos.empty? %>
             <p>Питомец не отмечен на фотографиях</p>
           <% else %>
                  <%= f.fields_for :photos do |photo_form| %>
                       <div class="thumbnail span2 attached-thumb">
                         <%= photo_form.link_to_remove raw("<i class='icon-white icon-remove-circle'></i>"), :title => "Открепить фото" %>
                         <%= image_tag photo_form.object.image.url(:thumb) %>
                       </div>
                  <% end %>
           <% end %>
  </div>


  <div class="row">
    <div class="form-actions">
      <%= f.submit "Сохранить", :class => 'btn btn-primary' %>
      <%= link_to "Отмена", session[:back_url], :class => "btn btn-small" %>
    </div>
  </div>

<% end %>

app/views/admin/pets/_pets_table.html.erb
<table class="table table-bordered" id="table-pets">
  <thead>
    <tr>
      <th><span>Кличка</span></th>
      <th><span>Пол</span></th>
      <th><span>ДР</span></th>
      <th><span>Окрас</span></th>
      <th><span>Титулы</span></th>
      <th><span>Владелец</span></th>
      <th><span>Заводчик</span></th>
      <th><span>Питомник</span></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @pets.each do |pet| %>
    <tr>
      <td><%= pet.name %></td>

      <td><%= pet_sex(pet) %></td>

      <td><%= pet.born.strftime("%d.%m.%y") if pet.born.present? %></td>

      <td><%= pet.color %></td>

      <td><%= pet.title %></td>

      <td><%= pet_owner(pet) %></td>

      <td><%= pet.breeder_name if pet.breeder.present? %></td>

      <td><%= pet.kennel_name if pet.kennel.present? %></td>

      <td class="double-actions">
        <%= link_to raw("<i class='icon-camera'></i>"), admin_pet_path(pet), :class => "btn btn-small", :title => "Фотографии с питомцем '#{pet.name}'" %>
        <%= link_to raw("<i class='icon-edit'></i>"),
          edit_admin_pet_path(pet), :class => "btn btn-small", :title => "Редактировать питомца '#{pet.name}'" %>
        <%= link_to raw("<i class='icon-eye-open'></i>"),
          pet_path(pet), :class => "btn btn-small", :title => "Посмотреть питомца '#{pet.name}' на сайте" %>
        <%= link_to raw("<i class='icon-remove'></i>"), admin_pet_path(pet), :method => :delete, :class => "btn btn-small", :title => "Удалить питомца 'Bobby'", :confirm => "Вы уверены?" %>
      </td>

    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/pets/_sidenav.html.erb
<% active ||= '' %>
<div class="span2">
    <nav class="well" style="padding: 8px 0;">
        <ul class="nav nav-list">
          <li class="nav-header">Питомцы</li>

          <li class="<%== 'active' if active == 'my-pets' %>">
            <%= link_to "Мои питомцы", admin_pets_path(:search => {:owned => true}) %>
          </li>

          <li class="<%== 'active' if active == 'all-pets' %>">
            <%= link_to "Все питомцы", admin_pets_path %>
          </li>
          <li class="<%== 'active' if active == 'puppy-pets' %>">
            <%= link_to "Щенки", admin_pets_path(:search => {:puppy => true}) %>
          </li>

          <li class="<%== 'active' if active == 'owner' %>">
            <%= link_to "Владельцы", admin_people_path(:role => "owner") %>
          </li>

          <li class="<%== 'active' if active == 'breeder' %>">
            <%= link_to "Заводчики", admin_people_path(:role => "breeder") %>
          </li>

          <li class="<%== 'active' if active == 'kennel' %>">
            <%= link_to "Питомники", admin_people_path(:role => "kennel") %>
          </li>

          <li class="divider"></li>

          <li class="<%== 'active' if active == 'new-pet' %>">
            <%= link_to "Добавить питомца", new_admin_pet_path %>
          </li>
        </ul>
    </nav>
</div>

app/views/admin/pets/edit.html.erb
<div class="row">
  <%= render "sidenav" %>

  <div class="span10">
    <h1>Редактировать питомца</h1>
    <%= render "form", :pet => @pet %>
  </div>
</div>

app/views/admin/pets/index.html.erb
<div class="row">
  <%= render "sidenav", :active => active_admin_pets_menu(params[:search]) %>

  <div class="span10">
    <h1><%= admin_pets_header(params[:search]) %></h1>
    <div class="row">
      <div class="span10">
        <%= render "pets_table", :pets => @pets %>
      </div>
    </div>
  </div>
</div>

app/views/admin/pets/new.html.erb
<div class="row">
  <%= render "sidenav", :active => "new-pet" %>

  <div class="span10">
    <h1>Новый питомец</h1>
    <%= render "form", :pet => @pet %>
  </div>
</div>

app/views/admin/pets/show.html.erb
<div class="row">
    <%= render "sidenav" %>

  <div class="span10">
    <div class="pull-right actions">
      <%= link_to "Редактировать", edit_admin_pet_path(@pet), :class => "btn btn-small", :title => "Редактировать питомца '#{@pet.name}'" %>
    </div>
    <h1>
      <%= @pet.name %>
    </h1>
    <div class="row">
      <div class="span10">

        <%= render  "admin/shared/photos", :photos => @photos %>

      </div>
    </div>
  </div>
</div>