config/routes.rb
Kennel::Application.routes.draw do

  scope '/mercury' do
    match ':type/:resource' => "mercury#resource"
    match 'snippets/:name/options' => "mercury#snippet_options"
    match 'snippets/:name/preview' => "mercury#snippet_preview"
  end

  root :to => "home#main"

  resources :pets do
    resources :photos
  end
  resources :posts
  resources :photos

  match 'gallery' => 'albums#index', :as => :gallery

  resources :albums do
    resources :photos
  end

  match 'admin' => 'admin/dashboard#home', :as => :admin
  match 'admin/settings' => 'admin/settings#show' , :as => :admin_settings
  match 'admin/settings/update' => 'admin/settings#update'

  namespace :admin do
    root :to => "dashboard#home"
    resources :photos
    resources :posts
    resources :albums do
      resources :photos
      collection do
        post 'uploader'
      end
    end
    resources :pets
    resources :people
    resources :static_pages
  end

  match '/pages/*path', :to => 'static_content#show', :via => :get, :as => 'static_page'

end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
  attr_accessible :content, :name, :slug
  validates :name, :uniqueness => true
  validates :slug, :uniqueness => true
end

app/controllers/admin/static_pages_controller.rb
# -*- coding: utf-8 -*-
class Admin::StaticPagesController < Admin::ApplicationController
  before_filter :find_static_page, :except => [:index, :new, :create]
  after_filter :expire_cache, :only => [:update, :destroy]

  respond_to :html, :js

  def index
      @static_pages = StaticPage.order("created_at DESC").page params[:static_page]
  end

  def show
  end

  def edit
  end

  def new
    @static_page = StaticPage.new
  end

  def create
    @static_page = StaticPage.new(params[:static_page])
    @static_page.save
    redirect_to admin_static_pages_path
  end

  def update
    page = StaticPage.find(params[:id])
    attributes = params[:static_page] ? params[:static_page] : {}
    if params[:content]
      attributes.merge!(
        :name => params[:content][:static_page_name][:value],
        :content => params[:content][:static_page_content][:value]
      )
    end
    if page.update_attributes(attributes)
      flash[:info] = "Страница успешно обновлена"
      respond_with(page) do |format|
        format.html { redirect_to admin_static_pages_path }
        format.js   { render text: ""}
      end
    else
      flash[:error] = "Что-то пошло не так"
      redirect_to admin_static_pages_path
    end
    
  end

  def destroy
    @static_page.destroy
    redirect_to :back
  end

  private
  def find_static_page
    @static_page = StaticPage.find(params[:id])
  end

  def expire_cache
    expire_fragment :controller => '/static_content', :action => 'show', :path => @static_page.slug
  end
end

app/views/admin/static_pages/_form.html.erb
<%= form_for [:admin, static_page], :validate => true, :html => { :class => "form-horizontal" } do |f| %>

<div class="row">

  	  <% if static_page.new_record? %>
  	  <div class="alert alert-info span9">
        Вы сможете отредактировать содержимое страницы после её создания
      </div>
      <% end %>

      <div class="control-group">
         <label class="control-label">Заголовок</label>
         <div class="controls">
           <%= f.text_field :name, :class => "input-xlarge"  %>
         </div>
      </div>

      <div class="control-group">
         <label class="control-label">Ссылка</label>
         <div class="controls">
           <%= f.text_field :slug, :class => "input-xlarge"  %>
          <p class="help-block">используйте только латинские символы и нижнее подчёркивание (пр.: 'about', 'about_us')</p>
         </div>
      </div>

      <% unless static_page.new_record? %>
        <div class="control-group">
           <label class="control-label">Содержимое</label>
           <div class="controls">
             <%= link_to "Открыть редактор", static_page_path(:path => static_page.slug, :show_editor => true), :class => "btn" %>
           </div>
        </div>
      <% end %>
</div>

<div class="form-actions">
  <%= f.submit "Сохранить", :class => 'btn btn-primary' %>
  <%= link_to "Отмена", session[:back_url], :class => "btn btn-small" %>
</div>

<% end %>

app/views/admin/static_pages/_sidenav.html.erb
<% active ||= '' %>
<div class="span2">
    <nav class="well" style="padding: 8px 0;">
        <ul class="nav nav-list">
          <li class="nav-header">Страницы</li>
          <li class="<%== 'active' if active == 'all-pages' %>">
            <%= link_to "Все страницы", admin_static_pages_path %>
          </li>
          <li class="divider"></li>
          <li class="<%== 'active' if active == 'new-page' %>">
            <%= link_to "Добавить страницу", new_admin_static_page_path %>
          </li>
        </ul>
    </nav>
</div>

app/views/admin/static_pages/edit.html.erb
<div class="row">
<%= render "sidenav" %>

  <div class="span10">
    <h1>Редактировать страницу</h1>
    <%= render "form", :static_page => @static_page %>
  </div>
</div>

app/views/admin/static_pages/index.html.erb
<div class="row">
  <%= render "sidenav", :active => "all-pages" %>

  <div class="span10">
    <h1>Страницы</h1>
    <table class="table table-bordered" id="table-pets">
  <thead>
    <tr>
      <th><span>Заголовок</span></th>
      <th><span>Ссылка</span></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @static_pages.each do |page| %>
    <tr>
      <td><%= page.name %></td>
      <td><%= page.slug %></td>

      <td class="double-actions">
        <%= link_to raw("<i class='icon-edit'></i>"),
          edit_admin_static_page_path(page), :class => "btn btn-small", :title => "Редактировать страницу '#{page.name}'" %>
        <%= link_to raw("<i class='icon-eye-open'></i>"),
          static_page_path(:path => page.slug), :class => "btn btn-small", :title => "Посмотреть страницу '#{page.name}' на сайте" %>
        <%= link_to raw("<i class='icon-remove'></i>"), admin_static_page_path(page), :method => :delete, :class => "btn btn-small", :title => "Удалить страницу '#{page.name}'", :confirm => "Вы уверены?" %>
      </td>

    </tr>
    <% end %>
  </tbody>
</table>

  </div>
</div>

app/views/admin/static_pages/new.html.erb
<div class="row">
  <%= render "sidenav", :active => "new-page" %>

  <div class="span10">
    <h1>Новая запись</h1>
    <%= render "form", :static_page => @static_page %>
  </div>
</div>